version: '3'

services:
    app:
        container_name: spybird-app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - '8088:80'
        networks:
            - network
    db:
        container_name: spybird-db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: SpyBird
            MYSQL_USER: SpyBird
            MYSQL_PASSWORD: SpyBird-Database-Password
        ports:
            - '3306:3306'
        networks:
            - network
networks:
    network:
        driver: bridge
