version: "3"

services:
    app:
        container_name: ${PREFIX}-app
        restart: unless-stopped
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
            - db
        ports:
            - ${APP_PORT}:80
        networks:
            - network
        volumes:
            - ${LOCAL_PATH}:/var/www/SpyBird
    db:
        container_name: ${PREFIX}-db
        restart: unless-stopped
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - network
    phpmyadmin:
        container_name: ${PREFIX}-phpmyadmin
        restart: unless-stopped
        image: phpmyadmin:latest
        depends_on:
            - db
        ports:
            - ${PMA_PORT}:80
        networks:
            - network
networks:
    network:
        driver: bridge
        name: ${PREFIX}-network
